name: runap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

 #----------------PACKAGES----------------------------#
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: 2.5.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.70.2
  # Maps
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.0
  lottie: ^3.3.1
  connectivity_plus: ^5.0.1
  provider: ^6.1.2
  get_it: ^8.0.3


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specific
  carousel_slider: ^5.0.0

  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Local Storage
  shared_preferences: ^2.5.2

  #----------------- ./ PACKAGES END ---------------------#
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 #------------- LOCAL ASSETS -------------------#

  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/workout/
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/
    - assets/images/workouts/
    - assets/images/animations/
    - assets/icons/categories/

 #------------- LOCAL FONTS -------------------#

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800