// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsISH-c2eEwOJboWpxK2OXUrlpx5pXYck',
    appId: '1:524353907461:web:4ceb6659b1981c7590a56c',
    messagingSenderId: '524353907461',
    projectId: 'runap-2891c',
    authDomain: 'runap-2891c.firebaseapp.com',
    storageBucket: 'runap-2891c.firebasestorage.app',
    measurementId: 'G-CZBK5LR3YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQvwvzhSnFBfHEE3Ds8uX5jQgtJM_G1I',
    appId: '1:524353907461:android:6d0e0fddc9e6ea3890a56c',
    messagingSenderId: '524353907461',
    projectId: 'runap-2891c',
    storageBucket: 'runap-2891c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMyQZ9TN05abTw_4W2oOAJDXgpgPHYdw',
    appId: '1:524353907461:ios:884f63513dd9cc1c90a56c',
    messagingSenderId: '524353907461',
    projectId: 'runap-2891c',
    storageBucket: 'runap-2891c.firebasestorage.app',
    androidClientId: '524353907461-rum5p5jf3fbtv9m0eidjkpb7jdt3tbb6.apps.googleusercontent.com',
    iosClientId: '524353907461-q4upq504gdsotj0gni7md467aolfcmdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.runap',
  );

}